sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

before_install:
 - chmod +x gradlew

after_success:
  - docker build -t microservices/employees .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push foreverdockerized/microservices